
export const STARTAUTH='STARTAUTH';
export const ERRORAUTH= 'ERRORAUTH';
export const SETAUTHLOGIN='SETAUTHLOGIN';
export const SETAUTHFORGOTPASSWORD='SETAUTHFORGOTPASSWORD';
export const SETAUTHRESETPASSWORD='SETAUTHRESETPASSWORD';
export const SETAUTHGETME='SETAUTHGETME';
export const SETAUTHCHANGEPASS='SETAUTHCHANGEPASS';
export const SETAUTHSENDSMS= 'SETAUTHSENDSMS';
export const EXPIRESCODE= 'EXPIRESCODE';
export const SENDREQ= 'SENDREQ';
export const CHANGEROLE= 'CHANGEROLE';
export const STARTCHANGEROLE= 'STARTCHANGEROLE';
export const FINDPHONENUMBER = 'FINDPHONENUMBER';
export const GETADVISOR= 'GETADVISOR';
export const UPDATEPROFILE = "UPDATEPROFILE";

export const REALSTATEPOST='REALSTATEPOST';
export const REALSTATEGETALL= 'REALSTATEGETALL'
export const REALSTATEGETONE= 'REALSTATEGETONE'
export const REALSTATEPATCH= 'REALSTATEPATCH'
export const REALSTATEDELETEONE= 'REALSTATEDELETONE'
export const REALSTATESTART= 'REALSTATESTART'
export const REALSTATEERROR='REALSTATEERROR';
export const REALSTATEFOCUS= 'REALSTATEFOCUS'; 
export const REALSTATEFOCUSSTART= 'REALSTATEFOCUSSTART'; 
export const SAVETABSEARCHBOX = 'SAVETABSEARCHBOX';

export const CITYGETALL= 'CITYGETALL';
export const CITYGET= 'CITYGET';
export const CITYWRITE= 'CITYWRITE';
export const CITYDELETE= 'CITYDELETE';

export const AREAGETALL= 'AREAGETALL';
export const AREAGET= 'AREAGET';
export const AREAWRITE= 'AREAWRITE';
export const AREADELETE= 'AREADELETE';


export const WORKSAMPELSTART= 'WORKSAMPELSTART';
export const WORKSAMPELERROR= 'WORKSAMPELERROR';
export const WORKSAMPELGETALL= 'WORKSAMPELGETALL';
export const WORKSAMPELPOST= 'WORKSAMPELPOST';


export const GETALLREQ= 'GETALLREQ';
export const STARTREQ= 'STARTREQ';
export const PATCHREQ = 'PATCHREQ';
export const ALLREQ= 'ALLREQ';

export const GETALLFILTER= 'GETALLFILTER';
export const STARTGETALL= 'STARTGETALL';


export const REVIWEANDRATEPOSTS= 'REVIEWANDRATEPOSTS';
export const REVIWEGET= 'REVIWEGWT';
export const STARTRATE= 'STARTRATE';
export const  RATEPATCH= 'RATEPATCH';

export const APPOINTMENTSTART= 'APPOINTMENTSTART';
export const APPOINTMENTPOST= 'APPOINTMENTPOST';
export const APPOINTMENTGET= 'APPOINTMENTGET';
export const APPOINTMENTGETONE= 'APPOINTMENTGETONE';
export const APPOINTMENTUPDATE= 'APPOINTMENTUPDATE';

export const MARKSTART= 'MARKSTART';
export const GETALLMYMARK = 'GETALLMYMARK';
export const ADDMARK = 'ADDMARK';

export const GETBESTOFADVISOR = 'GETBESTOFADVISOR';

export const SEARCHFIELDSCHANGE = "SEARCHFIELDSCHANGE"; 


export const CLOSEMODAL = "CLOSEMODAL";